inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false

Layout/IndentationConsistency: 
  Enabled: true
  
Layout/IndentationWidth:
  Enabled: true
  Width: 2