tables:
  metrics:
    columns:
      id:
        type: uuid
        description: Primary key
      family_id:
        type: uuid 
        description: Reference to the family this metric belongs to
      account_id:
        type: uuid
        description: Optional reference to specific account this metric is for
      kind:
        type: string
        description: The type of metric being tracked
        possible_values:
          - "net_worth"
          - "spending"
      subkind:
        type: string
        description: Optional sub-classification of the metric kind
      date:
        type: date
        description: The date this metric value was recorded
      value:
        type: decimal
        description: The numeric value of the metric
    foreign_keys:
      - { column: family_id, references: families }
      - { column: account_id, references: accounts }

  families:
    columns:
      id:
        type: uuid
        description: Primary key
      name:
        type: string
        description: Display name for the family
      currency:
        type: string
        description: Base currency used for this family's finances
      last_synced_at:
        type: datetime
        description: When family accounts were last synced with external data
      locale:
        type: string
        description: Language/region settings for the family
      stripe_plan_id:
        type: string
        description: ID of the Stripe subscription plan
      stripe_customer_id:
        type: string
        description: ID of the family in Stripe's system
      stripe_subscription_status:
        type: string
        description: Current status of the family's subscription
      date_format:
        type: string
        description: Preferred date format for display
      country:
        type: string
        description: Country where the family is based

  accounts:
    columns:
      id:
        type: uuid
        description: Primary key
      subtype:
        type: string
        description: Further classification of the account type
      family_id:
        type: uuid
        description: Reference to the family this account belongs to
      name:
        type: string
        description: Display name for the account
      accountable_type:
        type: string
        description: Polymorphic type for the specific account implementation
      accountable_id:
        type: uuid
        description: Polymorphic ID for the specific account implementation
      balance:
        type: decimal
        description: Current balance of the account
      currency:
        type: string
        description: Currency the account operates in
      is_active:
        type: boolean
        description: Whether the account is currently active
      last_sync_date:
        type: date
        description: When the account was last synced with external data
      institution_id:
        type: uuid
        description: Reference to the financial institution for this account
      classification:
        type: string
        description: Whether account is an asset or liability
      import_id:
        type: uuid
        description: Reference to import that created this account
      mode:
        type: string
        description: Operating mode of the account
    foreign_keys:
      - { column: family_id, references: families }
      - { column: institution_id, references: institutions }
      - { column: import_id, references: imports }

  account_balances:
    columns:
      id:
        type: uuid
        description: Primary key
      account_id:
        type: uuid
        description: Reference to the account this balance is for
      date:
        type: date
        description: Date this balance was recorded
      balance:
        type: decimal
        description: The account balance amount
      currency:
        type: string
        description: Currency of the balance amount
      cash_balance:
        type: decimal
        description: Optional cash balance for investment accounts
    foreign_keys:
      - { column: account_id, references: accounts, on_delete: cascade }

  account_entries:
    columns:
      id:
        type: uuid
        description: Primary key
      account_id:
        type: uuid
        description: Reference to the account this entry belongs to
      entryable_type:
        type: string
        description: Type of entry (Account::Transaction, Account::Valuation, Account::Trade)
      entryable_id:
        type: uuid
        description: ID of the specific entry record
      date:
        type: date
        description: Date of the entry
      name:
        type: string
        description: Original name/description of the entry
      enriched_name:
        type: string
        description: Enhanced/cleaned name of the entry
      amount:
        type: decimal
        description: Amount of the entry (negative for inflows, positive for outflows)
      currency:
        type: string
        description: Currency of the entry
      notes:
        type: text
        description: Additional notes about the entry
      import_id:
        type: uuid
        description: Optional reference to import that created this entry
      plaid_id:
        type: string
        description: Optional reference to external Plaid transaction ID
    foreign_keys:
      - { column: account_id, references: accounts }
      - { column: import_id, references: imports }

  account_transactions:
    columns:
      id:
        type: uuid
        description: Primary key
      category_id:
        type: uuid
        description: Optional reference to transaction category
      merchant_id:
        type: uuid
        description: Optional reference to merchant
      excluded:
        type: boolean
        description: Whether this transaction is excluded from calculations
    foreign_keys:
      - { column: category_id, references: categories }
      - { column: merchant_id, references: merchants }

  categories:
    columns:
      id:
        type: uuid
        description: Primary key
      family_id:
        type: uuid
        description: Reference to the family this category belongs to
      name:
        type: string
        description: Display name of the category
      color:
        type: string
        description: Color code for the category
      classification:
        type: string
        description: Type of category (expense, income)
      parent_id:
        type: uuid
        description: Optional reference to parent category
    foreign_keys:
      - { column: family_id, references: families }
      - { column: parent_id, references: categories }

  merchants:
    columns:
      id:
        type: uuid
        description: Primary key
      family_id:
        type: uuid
        description: Reference to the family this merchant belongs to
      name:
        type: string
        description: Display name of the merchant
      color:
        type: string
        description: Color code for the merchant
      icon_url:
        type: string
        description: URL to merchant's icon/logo
      enriched_at:
        type: datetime
        description: When merchant data was last enriched
    foreign_keys:
      - { column: family_id, references: families }

  tags:
    columns:
      id:
        type: uuid
        description: Primary key
      family_id:
        type: uuid
        description: Reference to the family this tag belongs to
      name:
        type: string
        description: Display name of the tag
      color:
        type: string
        description: Color code for the tag
    foreign_keys:
      - { column: family_id, references: families }

  taggings:
    columns:
      id:
        type: uuid
        description: Primary key
      tag_id:
        type: uuid
        description: Reference to the tag
      taggable_type:
        type: string
        description: Type of record being tagged
      taggable_id:
        type: uuid
        description: ID of record being tagged
    foreign_keys:
      - { column: tag_id, references: tags }
